---
language: node_js

node_js:
  - "node"

env:
  - BROCCOLI_ENV=test

sudo: false

addons:
  apt:
    packages:
    - build-essential

before_script:
  - npm install -g broccoli-cli jspm
  - npm install
  - jspm install

script: broccoli build travis
