language: node_js

node_js:
  - stable

deploy:
  api-key:
    secure: rvJg6JPIuathpIOhuZ/lISXHB4MbB4ihzoNDmNkSVIruPbNR7m4QMJfMP1oBX0bL1vAUnqjQqRHYQ8xJ3iE93K/tTl4HUHnRcgKAsyeYbl2Va4suZS/0S9am+k4zr2VLJtoA6104BhtKRNgYAOTdnWnz8HoFMZ43HeqS5h7KiOct3skMo/c6wswoKdb5JkRwQWSHZvrbMzEr7Xe3OyYN2s3JOXcBlRAqS6aiLivw/ELu+6VjaPQLieSfnBBc3z/Z/xAD/1PJaPxy6duLkq06/GSN55qQ4Sd013sqR5urxUEW8mGAasqNxkjZ2ol9R9WMGcibvV5EacCgAs6J6ufyHVsuqDH/LvP7Me0zGIOed34JJyMlso5lFW62guON6CdfnHDBPEEdmUf88SdWeS53Lt4s1pbbmMLHa+Q9QSlog6EVR+4iwaC2IxsLzGtSp5iDftq4y7GFlkjUhMwdMcgjQBz8Jd2Kdb+HRxvDGyhe2uPpwcx8V2OH2BP1eGikzGWqBmPcMRuXCjSPuF8RH5fpsYS1JWQb6XYzzcnNE/zFVKipii/yHeZn81rBQ8/L9ARXhMBu74fy0D6s+c0XxJh3l2GacoWqwPtHjaDiqHvX2wS610Mx/QCTqSTLY6uOAKsgWmYlr5Xz0Y6OKTV0WcgOfENI18LhflBwoEew95U5hBg=

env:
  matrix:
  - NODE_ENV=development
  global:
    secure: RB969KX5sTbwAIOeF+tqg7EsV8GO5GuyV1mS0mulYuMk8pG/iDAzaImAqkYetFtRruyXe8VaweqimnO7OHX8CmGqPuUIoS1Yis4aeN7CcR502Ug8BKnRjYmHLq6YJckMB0FHue/sTro7vFfSXrhdLa4se8zXUScAfY+3nm9FmsT5tkY1MAsIwPrJqYrAQYfk/a0te1nKC1YPlsapjVSYF9bYgSAlW7QrRvh8AjG6X472MfbD10e9pA2cro5Fj1JFqEt6uk87ZXH6ZzNjCPbDFLdh3wNZCy+gxxAxVTJ/d1XRe0Yo/Hn1Kzt9S/GbLyhJlZ0nqCA1nvQCsBGsH6ED49UHQmJ9kJ3qWkqYAjnn2jC8aY/HUZiZlBHrr7227vxMiPR/pdXIE910VSYc0gMKxAQwIo4SOIZHhRpcCVAHJ/tuuQAxIdUZ/0y74aB2F22nybk1EgkeJxqwPbI8lvf8R4vyzwGgz4+NoW2ebY6wo+r8XZpz1AtoelFSNyGsGBiKAoxlu300FOm8fBKWPFtuw1aIPQjNZUkYVhkGjV5eEP+I4jNsTp9KuxN/KO+8B7B7jTTYVNCQzv3ibMnu8S45JT4VuBjt2PvRtAtAxyQY0U8Oe++6FZnyuAoT44Y22HSLT/XqO9QBuFCq17hQSv7VSzFm0h7/WR7NjQAqbwqv2xs=

sudo: false

cache:
  - apt: true
  - directories:
    - node_modules
    - glint-dashboard/node_modules
    - glint-dashboard/jspm_packages
    - glint-lib/node_modules
    - glint-server/node_modules

addons:
  apt:
    packages:
    - build-essential
    - libzmq3
    - libzmq3-dev

before_script:
  - npm install -g gulp jspm
  - jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN

script: ./build.sh
