language: node_js

node_js:
  - node

deploy:
  api-key:
    secure: rvJg6JPIuathpIOhuZ/lISXHB4MbB4ihzoNDmNkSVIruPbNR7m4QMJfMP1oBX0bL1vAUnqjQqRHYQ8xJ3iE93K/tTl4HUHnRcgKAsyeYbl2Va4suZS/0S9am+k4zr2VLJtoA6104BhtKRNgYAOTdnWnz8HoFMZ43HeqS5h7KiOct3skMo/c6wswoKdb5JkRwQWSHZvrbMzEr7Xe3OyYN2s3JOXcBlRAqS6aiLivw/ELu+6VjaPQLieSfnBBc3z/Z/xAD/1PJaPxy6duLkq06/GSN55qQ4Sd013sqR5urxUEW8mGAasqNxkjZ2ol9R9WMGcibvV5EacCgAs6J6ufyHVsuqDH/LvP7Me0zGIOed34JJyMlso5lFW62guON6CdfnHDBPEEdmUf88SdWeS53Lt4s1pbbmMLHa+Q9QSlog6EVR+4iwaC2IxsLzGtSp5iDftq4y7GFlkjUhMwdMcgjQBz8Jd2Kdb+HRxvDGyhe2uPpwcx8V2OH2BP1eGikzGWqBmPcMRuXCjSPuF8RH5fpsYS1JWQb6XYzzcnNE/zFVKipii/yHeZn81rBQ8/L9ARXhMBu74fy0D6s+c0XxJh3l2GacoWqwPtHjaDiqHvX2wS610Mx/QCTqSTLY6uOAKsgWmYlr5Xz0Y6OKTV0WcgOfENI18LhflBwoEew95U5hBg=

env:
  matrix:
    - BROCCOLI_ENV=development
  global:
    secure: IaDG+DzxBBcoCXNr6JX1BCHyRu3LBIRKoAtCxy44/BM1Es0uEr+W9OtC16h2dN8TEQK2n3bxKlr7Z/fnYJi5SxXfjiL4NLSAxBfQLYjjRcYQBFMz0Cwgp/LFbETqOjJ//KK7gIXRM0DmdjV2I8yWlzfK9bn86UK3+9FerRA3CroYhcjnh20Twb6Uv2ASyWB2kI++qf4rkxTfG7CGGhRyOqsJn+O8oVFTHPgOQdf2wI1QsGNcBvGFBvqspWrNWSjY/lS4YkH0GmrTS/oIMPSZtP9wJA7IynwZZ0/bM9U+WRQHLS1YeddH3+8gM68VuTHh7C56QRtyu6/D4hj0vhsb2iAA+eiDPttYwQDgafocmDVmtDycHIokr2VG4gFA+8vfxOLYlsUC7pEi+arPd2cyVeZm0Y76aLN11IKXsqiLTu1Yf7kLn5OpTowxpJxlXvhzZHThIML0DBvcgEVHwvysXdk1LiTZ4P5S1NyfcUvPE2Ce5dM2aj8/jjhl7VtChv1+/ma7OIZydRXadeFhiV0l997ejIp0P1QKKGqU8OQCfERBCaLxQIjQp3cUjz3z+mlnm8XNGCWf5/KgK6Jk11Lb6UAuyOHpQTLCvszrFwcMIbww2Ajwk6DFHhIrvM1PdpaA21vl8HwttNBBcSrgZ/eCmujSeZYeub6Z6gJFbpl08Qo=

sudo: false

cache:
  - apt
  - directories:
    - node_modules
    - jspm_packages

addons:
  apt:
    packages:
    - build-essential

before_script:
  - npm install -g broccoli-cli jspm
  - npm install
  - jspm install

script: broccoli build travis
