sudo: false

language: node_js

node_js:
  - "6"

env:
  global:
    - CXX=g++-4.8
  matrix:
    - NODE_ENV=development

cache:
  - apt: true
  - directories:
    - node_modules
    - glint-client/node_modules
    - glint-server/node_modules
    - glint-dashboard/node_modules
    - glint-dashboard/glint-dashboard-server/node_modules
    - glint-dashboard/glitn-dashboard-ui/node_modules


addons:
  apt:
    packages:
    - build-essential
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

before_script:
  - npm install -g gulp node-gyp codecov mr-doc

script:
  - ./build.sh
