---
language: node_js

node_js:
  - "node"

env:
  - BROCCOLI_ENV=test

sudo: true

before_script:
  - sudo apt-get update
  - sudo apt-get install -y build-essential
  - npm install -g broccoli-cli jspm
  - npm install
  - jspm install

script: broccoli build travis
