language: node_js

node_js:
  - node

env:
  matrix:
  - BROCCOLI_ENV=development

sudo: false

cache:
  - apt
  - directories:
    - node_modules
    - jspm_packages

addons:
  apt:
    packages:
    - build-essential

before_script:
  - npm install -g broccoli-cli jspm
  - npm install
  - jspm install

script: broccoli build travis

deploy:
  api-key:
    secure: rvJg6JPIuathpIOhuZ/lISXHB4MbB4ihzoNDmNkSVIruPbNR7m4QMJfMP1oBX0bL1vAUnqjQqRHYQ8xJ3iE93K/tTl4HUHnRcgKAsyeYbl2Va4suZS/0S9am+k4zr2VLJtoA6104BhtKRNgYAOTdnWnz8HoFMZ43HeqS5h7KiOct3skMo/c6wswoKdb5JkRwQWSHZvrbMzEr7Xe3OyYN2s3JOXcBlRAqS6aiLivw/ELu+6VjaPQLieSfnBBc3z/Z/xAD/1PJaPxy6duLkq06/GSN55qQ4Sd013sqR5urxUEW8mGAasqNxkjZ2ol9R9WMGcibvV5EacCgAs6J6ufyHVsuqDH/LvP7Me0zGIOed34JJyMlso5lFW62guON6CdfnHDBPEEdmUf88SdWeS53Lt4s1pbbmMLHa+Q9QSlog6EVR+4iwaC2IxsLzGtSp5iDftq4y7GFlkjUhMwdMcgjQBz8Jd2Kdb+HRxvDGyhe2uPpwcx8V2OH2BP1eGikzGWqBmPcMRuXCjSPuF8RH5fpsYS1JWQb6XYzzcnNE/zFVKipii/yHeZn81rBQ8/L9ARXhMBu74fy0D6s+c0XxJh3l2GacoWqwPtHjaDiqHvX2wS610Mx/QCTqSTLY6uOAKsgWmYlr5Xz0Y6OKTV0WcgOfENI18LhflBwoEew95U5hBg=
