glint-server:
  build: ./glint-server/
  ports:
    - 8888:8888
  volumes:
    - ..:/opt/glint
  links:
    - etcd
    - graphite-statsd
  command:

nginx:
  image: nginx
  ports:
   - 3000:3000
  volumes:
   - ..:/opt/glint
   - nginx:/etc/nginx/conf.d
  links:
    - glint-server

graphite-statsd:
  image: hopsoft/graphite-statsd
  ports:
    - 8888:80
    - 2003:2003
    - 8125:8125
    - 8126:8126

etcd:
  image: quay.io/coreos/etcd:v2.2.1
  name: etcd
  command: -advertise-client-urls=http://0.0.0.0:2379 -listen-client-urls=http://0.0.0.0:2379
